const test = require('ava');
const Deck = require('../lib/Deck');

test('Creates a deck', t => {
  t.plan(2);
  const deck = new Deck();
  t.deepEqual(deck.minorArcana, [
    { arcana: 'minor', name: 'ace', number: 1, suit: 'wands' },
    { arcana: 'minor', name: '2', number: 2, suit: 'wands' },
    { arcana: 'minor', name: '3', number: 3, suit: 'wands' },
    { arcana: 'minor', name: '4', number: 4, suit: 'wands' },
    { arcana: 'minor', name: '5', number: 5, suit: 'wands' },
    { arcana: 'minor', name: '6', number: 6, suit: 'wands' },
    { arcana: 'minor', name: '7', number: 7, suit: 'wands' },
    { arcana: 'minor', name: '8', number: 8, suit: 'wands' },
    { arcana: 'minor', name: '9', number: 9, suit: 'wands' },
    { arcana: 'minor', name: '10', number: 10, suit: 'wands' },
    { arcana: 'minor', name: 'page', number: 11, suit: 'wands' },
    { arcana: 'minor', name: 'knight', number: 12, suit: 'wands' },
    { arcana: 'minor', name: 'queen', number: 13, suit: 'wands' },
    { arcana: 'minor', name: 'king', number: 14, suit: 'wands' },
    { arcana: 'minor', name: 'ace', number: 1, suit: 'pentacles' },
    { arcana: 'minor', name: '2', number: 2, suit: 'pentacles' },
    { arcana: 'minor', name: '3', number: 3, suit: 'pentacles' },
    { arcana: 'minor', name: '4', number: 4, suit: 'pentacles' },
    { arcana: 'minor', name: '5', number: 5, suit: 'pentacles' },
    { arcana: 'minor', name: '6', number: 6, suit: 'pentacles' },
    { arcana: 'minor', name: '7', number: 7, suit: 'pentacles' },
    { arcana: 'minor', name: '8', number: 8, suit: 'pentacles' },
    { arcana: 'minor', name: '9', number: 9, suit: 'pentacles' },
    { arcana: 'minor', name: '10', number: 10, suit: 'pentacles' },
    { arcana: 'minor', name: 'page', number: 11, suit: 'pentacles' },
    { arcana: 'minor', name: 'knight', number: 12, suit: 'pentacles' },
    { arcana: 'minor', name: 'queen', number: 13, suit: 'pentacles' },
    { arcana: 'minor', name: 'king', number: 14, suit: 'pentacles' },
    { arcana: 'minor', name: 'ace', number: 1, suit: 'cups' },
    { arcana: 'minor', name: '2', number: 2, suit: 'cups' },
    { arcana: 'minor', name: '3', number: 3, suit: 'cups' },
    { arcana: 'minor', name: '4', number: 4, suit: 'cups' },
    { arcana: 'minor', name: '5', number: 5, suit: 'cups' },
    { arcana: 'minor', name: '6', number: 6, suit: 'cups' },
    { arcana: 'minor', name: '7', number: 7, suit: 'cups' },
    { arcana: 'minor', name: '8', number: 8, suit: 'cups' },
    { arcana: 'minor', name: '9', number: 9, suit: 'cups' },
    { arcana: 'minor', name: '10', number: 10, suit: 'cups' },
    { arcana: 'minor', name: 'page', number: 11, suit: 'cups' },
    { arcana: 'minor', name: 'knight', number: 12, suit: 'cups' },
    { arcana: 'minor', name: 'queen', number: 13, suit: 'cups' },
    { arcana: 'minor', name: 'king', number: 14, suit: 'cups' },
    { arcana: 'minor', name: 'ace', number: 1, suit: 'swords' },
    { arcana: 'minor', name: '2', number: 2, suit: 'swords' },
    { arcana: 'minor', name: '3', number: 3, suit: 'swords' },
    { arcana: 'minor', name: '4', number: 4, suit: 'swords' },
    { arcana: 'minor', name: '5', number: 5, suit: 'swords' },
    { arcana: 'minor', name: '6', number: 6, suit: 'swords' },
    { arcana: 'minor', name: '7', number: 7, suit: 'swords' },
    { arcana: 'minor', name: '8', number: 8, suit: 'swords' },
    { arcana: 'minor', name: '9', number: 9, suit: 'swords' },
    { arcana: 'minor', name: '10', number: 10, suit: 'swords' },
    { arcana: 'minor', name: 'page', number: 11, suit: 'swords' },
    { arcana: 'minor', name: 'knight', number: 12, suit: 'swords' },
    { arcana: 'minor', name: 'queen', number: 13, suit: 'swords' },
    { arcana: 'minor', name: 'king', number: 14, suit: 'swords' },
  ]);
  t.deepEqual(deck.majorArcana, [
    { arcana: 'major', name: 'The Fool', number: 0 },
    { arcana: 'major', name: 'The Magician', number: 1 },
    { arcana: 'major', name: 'The High Priestess', number: 2 },
    { arcana: 'major', name: 'The Empress', number: 3 },
    { arcana: 'major', name: 'The Emporer', number: 4 },
    { arcana: 'major', name: 'The Hierophant', number: 5 },
    { arcana: 'major', name: 'The Lovers', number: 6 },
    { arcana: 'major', name: 'The Chariot', number: 7 },
    { arcana: 'major', name: 'Justice', number: 8 },
    { arcana: 'major', name: 'Hermit', number: 9 },
    { arcana: 'major', name: 'Wheel of Fortune', number: 10 },
    { arcana: 'major', name: 'Strength', number: 11 },
    { arcana: 'major', name: 'The Hanged Man', number: 12 },
    { arcana: 'major', name: 'Death', number: 13 },
    { arcana: 'major', name: 'Temperance', number: 14 },
    { arcana: 'major', name: 'The Devil', number: 15 },
    { arcana: 'major', name: 'The Tower', number: 16 },
    { arcana: 'major', name: 'The Star', number: 17 },
    { arcana: 'major', name: 'The Moon', number: 18 },
    { arcana: 'major', name: 'The Sun', number: 19 },
    { arcana: 'major', name: 'Judgement', number: 20 },
    { arcana: 'major', name: 'The World', number: 21 },
  ]);
});
