module.exports = {
  majorArcana: {
    symbols: [
      'The Fool',
      'The Magician',
      'The High Priestess',
      'The Empress',
      'The Emporer',
      'The Hierophant',
      'The Lovers',
      'The Chariot',
      'Justice',
      'Hermit',
      'Wheel of Fortune',
      'Strength',
      'The Hanged Man',
      'Death',
      'Temperance',
      'The Devil',
      'The Tower',
      'The Star',
      'The Moon',
      'The Sun',
      'Judgement',
      'The World',
    ],
  },
  minorArcana: {
    suits: [
      'wands',
      'pentacles',
      'cups',
      'swords',
    ],
    orders: [
      'ace',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      'page',
      'knight',
      'queen',
      'king',
    ],
  },
};
